// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***********',
    appId: '1:******:android:*********',
    messagingSenderId: '*******',
    projectId: '*****-****',
    databaseURL: 'https://******-****-default-rtdb.firebaseio.com',
    storageBucket: '********-*********.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***********',
    appId: '1:********:ios:*******',
    messagingSenderId: '*******',
    projectId: '****-*****',
    databaseURL: 'https://*****-******-default-rtdb.firebaseio.com',
    storageBucket: '********-*****.firebasestorage.app',
    iosBundleId: 'com.carlink.userapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***********',
    appId: '1:******:web:*********',
    messagingSenderId: '*******',
    projectId: '*****-****',
    authDomain: '*****-****.firebaseapp.com',
    databaseURL: 'https://******-****-default-rtdb.firebaseio.com',
    storageBucket: '********-*********.firebasestorage.app',
  );

}